phrases:
  bot_name: Sylph
  register_clan: ^(?P<clanName>[\s\S]+)ã‚’ç™»éŒ²ã—ã¦$
  create_challenge_report: å‡¸å ±å‘Šå ´æ‰€ã‚’ä½œã£ã¦
  challenge_report_guide: |-
    å‡¸ã‚’ã—ãŸã‚‰å›æ•°ã«å¿œã˜ã¦ã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
    æŒã¡è¶Šã—ã‚’æŒã£ãŸã‚‰1å›ç›®ã¯é’ã€2å›ç›®ã¯ç·‘ã®ãƒã‚§ãƒƒã‚¯ãƒãƒ¼ã‚¯ã«ã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
    ã‚¿ã‚¹ã‚­ãƒ«ã‚’ä½¿ã£ãŸã‚‰é»„è‰²ã„è­¦å‘Šã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
  days_unit: '{0}æ—¥ç›®'
  first_challenge_stamp: 1ï¸âƒ£
  second_challenge_stamp: 2ï¸âƒ£
  third_challenge_stamp: 3ï¸âƒ£
  first_carry_over_stamp: â˜‘ï¸
  second_carry_over_stamp: âœ…
  task_kill_stamp: âš ï¸
  succeed_reaction: ğŸ‘
  failed_reaction: ğŸ¥º