phrases:
  bot_name: Sylph
  register_clan: \[(?P<clanName>[\s\S]+)\]ã‚’ç™»éŒ²ã—ã¦
  register_members: \[(?P<clanName>[\s\S]+)\]ã®ãƒ¡ãƒ³ãƒãƒ¼ã‚’ç™»éŒ²ã—ã¦
  create_challenge_report: \[(?P<clanName>[\s\S]+)\]ã®å‡¸å ±å‘Šå ´æ‰€ã‚’ä½œã£ã¦
  register_webhook: \[(?P<clanName>[\s\S]+)\]ã®çŠ¶æ³ãŒå¤‰åŒ–ã—ãŸã‚‰ \[(?P<url>https?://[\w!\?/\+\-_~=;\.,\*&@#\$%\(\)'\[\]]+)\] ã«é€šçŸ¥ã—ã¦
  create_boss_questionnaire: ãƒœã‚¹ã‚¢ãƒ³ã‚±ãƒ¼ãƒˆä½œã£ã¦
  boss_notification_command: (?P<bossNumber>[1-5])ã«è¡ŒããŸã„äººã«é€šçŸ¥ã—ã¦
  challenge_report_guide: |-
    å‡¸ã‚’ã—ãŸã‚‰å›æ•°ã«å¿œã˜ã¦ã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
    æŒã¡è¶Šã—ã‚’æŒã£ãŸã‚‰1å›ç›®ã¯é’ã€2å›ç›®ã¯ç·‘ã®ãƒã‚§ãƒƒã‚¯ãƒãƒ¼ã‚¯ã«ã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
    ã‚¿ã‚¹ã‚­ãƒ«ã‚’ä½¿ã£ãŸã‚‰é»„è‰²ã„è­¦å‘Šã‚¹ã‚¿ãƒ³ãƒ—ã‚’æŠ¼ã—ã¦ã­ã€‚
  days_unit: '{0}æ—¥ç›®'
  boss_questionnaire_message: è¡ŒããŸã„ãƒœã‚¹ã®ã‚¹ã‚¿ãƒ³ãƒ—æŠ¼ã—ã¦ã­
  boss_notify_message: ãƒœã‚¹ã®å‡¸ã‚’é–‹å§‹ã™ã‚‹ã‚ˆ
  cannot_find_boss_questionnaire_message: ãƒœã‚¹ã‚¢ãƒ³ã‚±ãƒ¼ãƒˆãŒè¦‹ã¤ã‹ã‚‰ãªã„ã‚ˆã€‚1000å€‹ä»¥ä¸Šå‰ã®ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã¯è¦‹ã¤ã‘ã‚‰ã‚Œãªã„ã‹ã‚‰ã€æ–°ã—ãã‚¢ãƒ³ã‚±ãƒ¼ãƒˆã‚’ä½œã£ã¦ã­ã€‚
  first_challenge_stamp: 1ï¸âƒ£
  second_challenge_stamp: 2ï¸âƒ£
  third_challenge_stamp: 3ï¸âƒ£
  first_carry_over_stamp: â˜‘ï¸
  second_carry_over_stamp: âœ…
  task_kill_stamp: âš ï¸
  succeed_reaction: ğŸ‘
  failed_reaction: ğŸ¥º
  1_boss_stamp: 1ï¸âƒ£
  2_boss_stamp: 2ï¸âƒ£
  3_boss_stamp: 3ï¸âƒ£
  4_boss_stamp: 4ï¸âƒ£
  5_boss_stamp: 5ï¸âƒ£